/*
 * config.h — hand-written for the libgphoto2 iOS xcframework build.
 *
 * Normally generated by autoconf/meson. For iOS we build a curated subset
 * (core + libgphoto2_port + camlibs/ptp2) directly with clang, so we pin the
 * feature macros for the iOS/Darwin (arm64, little-endian) target here.
 *
 * Deliberately NOT defined (each has a reason):
 *   HAVE_LTDL      → no dlopen on iOS; replaced by stub ltdl.h + ltdl_static.c
 *   HAVE_LIBEXIF   → no libexif; the EXIF-mtime path in gphoto2-filesys.c is disabled
 *   HAVE_LIBXML2   → olympus-wrap.c is excluded (Olympus XML wrap, not needed for Canon)
 *   HAVE_LIBUSB*   → transport is ImageCaptureCore, not libusb
 *   HAVE_MULTI / HAVE_SERIAL / HAVE_TTYLOCK / HAVE_LOCKDEV / HAVE_RESMGR
 *   ENABLE_NLS     → i18n.h then stubs _()/N_()/gettext to identity (no libintl)
 *   WORDS_BIGENDIAN→ arm64 is little-endian
 */
#ifndef GP_IOS_CONFIG_H
#define GP_IOS_CONFIG_H

#define PACKAGE          "libgphoto2"
#define PACKAGE_NAME     "libgphoto2"
#define PACKAGE_TARNAME  "libgphoto2"
#define PACKAGE_VERSION  "2.5.34.1"
#define VERSION          "2.5.34.1"
#define GETTEXT_PACKAGE               "libgphoto2-6"
#define GETTEXT_PACKAGE_LIBGPHOTO2      "libgphoto2-6"
#define GETTEXT_PACKAGE_LIBGPHOTO2_PORT "libgphoto2_port-0"

#define HAVE_CC "clang (libgphoto2 iOS xcframework build)"

/* The set of camlibs/iolibs compiled in (normally generated). */
#define GP_CAMLIB_SET "ptp2"
#define IOLIB_LIST    "iccamera"

/* Platform capabilities present in the iOS/Darwin SDK. */
#define HAVE_UNISTD_H     1
#define HAVE_LIMITS_H     1
#define HAVE_SYS_PARAM_H  1
#define HAVE_LANGINFO_H   1
#define HAVE_ICONV        1
#define HAVE_GMTIME_R     1
#define HAVE_LOCALTIME_R  1
#define HAVE_VA_COPY      1
#define HAVE_SETENV       1
#define HAVE_INET_ATON    1
#define HAVE_STRDUP       1
#define HAVE_STRNDUP      1
#define HAVE_REGEX        1

/* Camlib/iolib search dirs: unused on iOS (static registration) but referenced
 * as string literals when the CAMLIBS/IOLIBS env vars are unset. */
#define CAMLIBS "."
#define IOLIBS  "."

/* Path macros normally supplied by the build; unused at runtime on iOS. */
#define LOCALEDIR "."

#endif /* GP_IOS_CONFIG_H */
